spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/subsidy_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
server:
  port: ${SERVER_PORT:8088}
