spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/jansetu?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
server:
  port: ${SERVER_PORT:8080}
