import { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import { grantApi } from './api';

const apiSchemeIds = { 'pm-kisan': 1, solar: 2, digital: 3, education: 4, housing: 5 };
const criteriaRules = {
  'pm-kisan': { limit: 200000, categories: ['All'], docs: ['Land Ownership Certificate', 'Aadhaar Card', 'Bank Passbook'] },
  solar: { limit: 800000, categories: ['All'], docs: ['Electricity Bill', 'Property Proof', 'Roof Layout Plan'] },
  digital: { limit: 500000, categories: ['All'], docs: ['Udyam MSME Registration', 'Business PAN', 'Bank Statements'] },
  education: { limit: 450000, categories: ['OBC', 'SC', 'ST', 'Minorities'], docs: ['12th Marksheet', 'Income Certificate', 'College Admission Proof'] },
  housing: { limit: 180000, categories: ['SC', 'ST', 'BPL'], docs: ['Ration Card', 'BPL Certificate', 'Site Photograph'] },
};

const schemes = [
  { id: 'pm-kisan', icon: '🌾', category: 'Agriculture', title: 'PM Farmer Income Support Scheme', short: 'PM-KISAN', amount: '₹6,000 / year', desc: 'Direct annual income support for small and marginal landholder farmers.', eligibility: ['Small or marginal landholder', 'Valid Aadhaar & bank account'], color: 'green' },
  { id: 'solar', icon: '☀️', category: 'Renewable energy', title: 'National Solar Rooftop Grant', short: 'Solar Rooftop', amount: '40% subsidy', desc: 'Support for installing residential rooftop solar panel systems.', eligibility: ['Owner-occupied residential home', 'Approved solar installation'], color: 'yellow' },
  { id: 'digital', icon: '⌘', category: 'Entrepreneurship', title: 'Digital Micro-Enterprise Empowerment Grant', short: 'Digital Enterprise', amount: 'Up to ₹50,000', desc: 'Financial support for local businesses adopting digital IT tools.', eligibility: ['Micro / small local business', 'Digital adoption proposal'], color: 'blue' },
  { id: 'education', icon: '🎓', category: 'Education', title: 'Higher Education Merit Subsidy', short: 'Merit Scholarship', amount: 'Full fee + stipend', desc: 'Tuition waiver and annual stipend for meritorious higher education students.', eligibility: ['Admission to higher education', 'Meets merit & income criteria'], color: 'purple' },
  { id: 'housing', icon: '⌂', category: 'Rural development', title: 'Rural Housing & Sanitation Grant', short: 'Rural Housing', amount: 'Up to ₹1.2 lakh', desc: 'Direct support for safe housing and modern sanitation construction.', eligibility: ['Rural household', 'No permanent pucca house'], color: 'terracotta' },
];

const blankProfile = { name: '', dob: '', gender: '', mobile: '', aadhaar: '', category: '', income: '', employment: '', state: '', district: '', village: '', bank: '', ifsc: '' };
const demoProfile = { name: 'Asha Ramesh Patil', dob: '1993-08-18', gender: 'Female', mobile: '9876543210', aadhaar: 'XXXX XXXX 4812', category: 'OBC', income: '180000', employment: 'Farmer', state: 'Maharashtra', district: 'Pune', village: 'Khed', bank: '245710003456', ifsc: 'SBIN0000456' };

function App() {
  const [screen, setScreen] = useState('login');
  const [profile, setProfile] = useState(blankProfile);
  const [login, setLogin] = useState('');
  const [menuOpen, setMenuOpen] = useState(false);
  const [applications, setApplications] = useState([{ schemeId: 'pm-kisan', stage: 2, applied: '12 Aug 2026', ref: 'DSG-2026-0812-409' }]);
  const [notice, setNotice] = useState('');
  const [criteria, setCriteria] = useState(null);
  const applied = id => applications.find(a => a.schemeId === id);
  const activeApplication = useMemo(() => applications[0], [applications]);

  const demo = () => { setProfile(demoProfile); setLogin('9876543210'); setScreen('dashboard'); };
  const saveProfile = e => { e.preventDefault(); setScreen('dashboard'); setNotice('Your beneficiary profile has been saved.'); };
  const apply = async schemeId => {
    if (applied(schemeId)) { setScreen('tracking'); return; }
    const scheme = schemes.find(s => s.id === schemeId); const rule = criteriaRules[schemeId];
    const local = { incomeEligible: Number(profile.income || 0) <= rule.limit, categoryEligible: rule.categories.includes('All') || rule.categories.includes(profile.category), maxIncomeLimit: rule.limit, allowedCategories: rule.categories, requiredDocuments: rule.docs, missingDocuments: [] };
    local.eligible = local.incomeEligible && local.categoryEligible; local.message = local.eligible ? 'You meet the scheme profile criteria.' : 'Your current profile does not meet the scheme criteria.';
    try { setCriteria({ scheme, result: await grantApi.validateCriteria(apiSchemeIds[schemeId], profile.id || 1, rule.docs) }); } catch { setCriteria({ scheme, result: local }); }
  };
  const checkCriteria = async scheme => {
    const rule = criteriaRules[scheme.id];
    const local = { incomeEligible: Number(profile.income || 0) <= rule.limit, categoryEligible: rule.categories.includes('All') || rule.categories.includes(profile.category), maxIncomeLimit: rule.limit, allowedCategories: rule.categories, requiredDocuments: rule.docs, missingDocuments: [], message: 'You meet the scheme profile criteria.' };
    local.eligible = local.incomeEligible && local.categoryEligible;
    try { setCriteria({ scheme, result: await grantApi.validateCriteria(apiSchemeIds[scheme.id], profile.id || 1, rule.docs) }); }
    catch { setCriteria({ scheme, result: local }); }
  };
  const confirmApplication = async () => { const scheme = criteria.scheme; const rule = criteriaRules[scheme.id]; try { await grantApi.submitApplication(profile.id || 1, apiSchemeIds[scheme.id], rule.docs); } catch {} setCriteria(null); setApplications([{ schemeId: scheme.id, stage: 0, applied: '01 Sep 2026', ref: `DSG-2026-0901-${Math.floor(100 + Math.random() * 900)}` }, ...applications]); setNotice('Application submitted successfully. You can track its progress below.'); setScreen('tracking'); };

  if (screen === 'login') return <Login login={login} setLogin={setLogin} demo={demo} enter={() => { setProfile(p => ({ ...p, mobile: login })); setScreen('profile'); }} />;
  const app = activeApplication;
  const appScheme = schemes.find(s => s.id === app?.schemeId);
  return <div className="app-shell">
    <Sidebar screen={screen} setScreen={setScreen} menuOpen={menuOpen} setMenuOpen={setMenuOpen} />
    <main className="main-content">
      <Topbar profile={profile} setMenuOpen={setMenuOpen} />
      {notice && <div className="notice"><span>✓</span>{notice}<button onClick={() => setNotice('')}>×</button></div>}
      {screen === 'profile' && <Profile profile={profile} setProfile={setProfile} saveProfile={saveProfile} />}
      {screen === 'dashboard' && <Dashboard profile={profile} schemes={schemes} applications={applications} apply={apply} checkCriteria={checkCriteria} setScreen={setScreen} />}
      {screen === 'schemes' && <Schemes schemes={schemes} applications={applications} apply={apply} checkCriteria={checkCriteria} />}
      {screen === 'tracking' && <Tracking app={app} scheme={appScheme} setScreen={setScreen} />}
      {criteria && <CriteriaModal scheme={criteria.scheme} result={criteria.result} close={() => setCriteria(null)} confirm={confirmApplication} />}
    </main>
  </div>;
}

function Login({ login, setLogin, demo, enter }) { return <div className="login-page"><div className="login-art"><div className="brand light"><span className="brand-mark">✦</span><span>JanSetu <em>beneficiary portal</em></span></div><div className="art-copy"><span className="eyebrow">DIGITAL SUBSIDY & GRANT PLATFORM</span><h1>Every benefit.<br /><i>Closer to home.</i></h1><p>A simpler way to discover, apply for, and track government support built around you.</p></div><div className="art-stats"><div><b>5</b><span>Active schemes</span></div><div><b>100%</b><span>Transparent tracking</span></div></div></div><section className="login-panel"><div className="login-form"><div className="brand mobile-brand"><span className="brand-mark">✦</span>JanSetu</div><div><span className="eyebrow">WELCOME TO JANSETU</span><h2>Sign in to your<br />beneficiary account</h2><p className="muted">Use your mobile number or Aadhaar / Citizen ID to continue.</p></div><label>Mobile number or Aadhaar / Citizen ID<input value={login} onChange={e => setLogin(e.target.value)} placeholder="Enter your ID" /></label><button className="primary full" onClick={enter}>Continue <span>→</span></button><button className="otp">▣ &nbsp; Sign in with OTP instead</button><div className="divider"><span>OR</span></div><button className="demo" onClick={demo}><span className="demo-icon">✦</span><span><b>Try Quick Demo</b><small>Explore with a pre-filled beneficiary profile</small></span><b>→</b></button><p className="secure">⌑ &nbsp; Your information is protected and secure</p></div></section></div> }

function Sidebar({ screen, setScreen, menuOpen, setMenuOpen }) { const items = [['dashboard','▦','Overview'],['schemes','◈','Explore schemes'],['tracking','⌁','Application tracking'],['profile','♙','My profile']]; return <aside className={menuOpen ? 'sidebar open' : 'sidebar'}><div className="brand"><span className="brand-mark">✦</span><span>JanSetu <em>beneficiary portal</em></span><button className="close" onClick={() => setMenuOpen(false)}>×</button></div><nav>{items.map(([key, icon, label]) => <button key={key} className={screen === key ? 'active' : ''} onClick={() => { setScreen(key); setMenuOpen(false); }}><i>{icon}</i>{label}</button>)}</nav><div className="sidebar-foot"><div className="help">?<span>Need help?<small>Contact support</small></span></div><button className="signout" onClick={() => location.reload()}>↪ Sign out</button></div></aside> }
function Topbar({ profile, setMenuOpen }) { return <header className="topbar"><button className="hamburger" onClick={() => setMenuOpen(true)}>☰</button><div className="breadcrumb">BENEFICIARY PORTAL <span>/</span> HOME</div><div className="top-user"><span className="bell">♧<i></i></span><span className="avatar">{(profile.name || 'B').slice(0,1)}</span><span><b>{profile.name || 'Beneficiary'}</b><small>Verified beneficiary</small></span></div></header> }

function Profile({ profile, setProfile, saveProfile }) { const update = (key, value) => setProfile({ ...profile, [key]: value }); const groups = [{title:'Personal details', desc:'Tell us a little about yourself.', fields:[['name','Full name','text'],['dob','Date of birth','date'],['gender','Gender','select'],['mobile','Mobile number','tel'],['aadhaar','Aadhaar ID number','text']]},{title:'Category & eligibility', desc:'This helps us find support that fits you.', fields:[['category','Social category','select'],['income','Annual family income (₹)','number'],['employment','Employment status','select']]},{title:'Location & bank details', desc:'Used to verify your eligibility and deliver benefits.', fields:[['state','State','select'],['district','District','text'],['village','Village / Town','text'],['bank','Bank account number','text'],['ifsc','IFSC code','text']]}]; return <section className="page profile-page"><PageTitle eyebrow="YOUR ACCOUNT" title={<>Complete your <b>profile</b></>} desc="A complete profile helps us show you the right schemes and enables direct benefit transfers." /><form onSubmit={saveProfile}>{groups.map(g => <div className="form-card" key={g.title}><div className="form-heading"><h3>{g.title}</h3><p>{g.desc}</p></div><div className="fields">{g.fields.map(([key,label,type]) => <label key={key}>{label}{type === 'select' ? <select value={profile[key]} onChange={e => update(key,e.target.value)} required><option value="">Select {label.toLowerCase()}</option>{options(key).map(v => <option key={v}>{v}</option>)}</select> : <input type={type} value={profile[key]} onChange={e => update(key,e.target.value)} placeholder={label} required={['name','mobile','state'].includes(key)} />}</label>)}</div></div>)}<div className="form-actions"><span>⌑ Your data is securely encrypted</span><button className="primary">Save profile & continue <b>→</b></button></div></form></section> }
function options(key) { return key === 'gender' ? ['Female','Male','Non-binary','Prefer not to say'] : key === 'category' ? ['General','OBC','SC','ST','Minorities'] : key === 'employment' ? ['Farmer','Self-employed','Employed','Student','Unemployed'] : ['Andhra Pradesh','Karnataka','Maharashtra','Tamil Nadu','Uttar Pradesh']; }
function PageTitle({ eyebrow, title, desc, action }) { return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{desc}</p></div>{action}</div> }

function Dashboard({ profile, schemes, applications, apply, setScreen }) { const latest = applications[0]; const scheme = schemes.find(s => s.id === latest.schemeId); return <section className="page"><PageTitle eyebrow="GOOD MORNING" title={<>Welcome back, <b>{(profile.name || 'Beneficiary').split(' ')[0]}.</b></>} desc="Here is a snapshot of your benefits and applications." action={<button className="outline" onClick={() => setScreen('schemes')}>Explore all schemes <b>→</b></button>} /><div className="summary-grid"><div className="summary green-summary"><span className="summary-icon">⌘</span><div><small>AVAILABLE FOR YOU</small><b>5 schemes</b><p>Based on your profile</p></div></div><div className="summary amber-summary"><span className="summary-icon">◷</span><div><small>ACTIVE APPLICATIONS</small><b>{applications.length} application{applications.length !== 1 && 's'}</b><p>Currently in process</p></div></div><div className="summary blue-summary"><span className="summary-icon">₹</span><div><small>FUNDS RECEIVED</small><b>₹1,800</b><p>Across all schemes</p></div></div></div><div className="two-col"><div className="panel status-panel"><div className="panel-head"><div><span className="eyebrow">LATEST APPLICATION</span><h3>{scheme.short}</h3></div><button className="text-button" onClick={() => setScreen('tracking')}>View tracking →</button></div><Progress stage={latest.stage} compact /><div className="status-meta"><span>Application no. <b>{latest.ref}</b></span><span className="pill amber">In field verification</span></div></div><div className="panel support-panel"><span className="support-emoji">💬</span><h3>Need a hand?</h3><p>Our beneficiary support team is here to help with any question.</p><button className="text-button">Get support →</button></div></div><section className="scheme-section"><div className="section-head"><div><span className="eyebrow">RECOMMENDED FOR YOU</span><h2>Find the support you need</h2></div><button className="text-button" onClick={() => setScreen('schemes')}>View all 5 schemes →</button></div><div className="scheme-grid">{schemes.slice(0,3).map(s => <SchemeCard key={s.id} scheme={s} applied={!!applications.find(a => a.schemeId === s.id)} apply={apply} />)}</div></section></section> }
function Schemes({ schemes, applications, apply }) { return <section className="page"><PageTitle eyebrow="GOVERNMENT SUPPORT" title={<>Explore <b>available schemes</b></>} desc="Find government benefits you may be eligible for, tailored to your profile." /><div className="scheme-grid full-grid">{schemes.map(s => <SchemeCard key={s.id} scheme={s} applied={!!applications.find(a => a.schemeId === s.id)} apply={apply} />)}</div></section> }
function SchemeCard({ scheme, applied, apply }) { return <article className={`scheme-card ${scheme.color}`}><div className="scheme-top"><span className="scheme-icon">{scheme.icon}</span><span className="category">{scheme.category}</span></div><h3>{scheme.title}</h3><p>{scheme.desc}</p><div className="grant"><small>BENEFIT AMOUNT</small><b>{scheme.amount}</b></div><div className="eligibility"><small>ELIGIBILITY</small>{scheme.eligibility.map(x => <span key={x}>✓ {x}</span>)}</div><button className={applied ? 'applied-button' : 'primary full'} onClick={() => apply(scheme.id)}>{applied ? 'View application →' : <>Apply now <span>→</span></>}</button></article> }
function Progress({ stage, compact }) { const steps = ['Application submitted','Field check','District approval','Funds disbursed']; return <div className={`progress ${compact ? 'compact' : ''}`}>{steps.map((step, i) => <div className="progress-step" key={step}><span className={i <= stage ? 'done' : ''}>{i < stage ? '✓' : i + 1}</span><p>{step}</p>{i < 3 && <i className={i < stage ? 'line done-line' : 'line'} />}</div>)}</div> }
function Tracking({ app, scheme, setScreen }) { if (!app) return <section className="page empty"><h1>No applications yet</h1><button className="primary" onClick={() => setScreen('schemes')}>Explore schemes</button></section>; const stages = [{name:'Stage 1 · Registration benefit',amount:'₹1,800',date:'Credited 14 Aug 2026',status:'Released',done:true},{name:'Stage 2 · Verification clearance',amount:'₹2,400',date:'Expected 25 Sep 2026',status:'Awaiting field check'},{name:'Stage 3 · Final approval',amount:'₹1,800',date:'Expected 15 Oct 2026',status:'Pending district approval'}]; return <section className="page tracking-page"><PageTitle eyebrow="APPLICATION TRACKING" title={<><b>{scheme.short}</b> application</>} desc={`Reference no. ${app.ref} · Submitted on ${app.applied}`} /><div className="tracking-hero"><div><span className="scheme-icon">{scheme.icon}</span><div><span className="eyebrow">CURRENT STATUS</span><h2>Field verification in progress</h2><p>Your application is with the local field officer for document and eligibility verification.</p></div></div><span className="pill amber">● In progress</span></div><div className="panel progress-panel"><h3>Application progress</h3><Progress stage={app.stage} /><div className="next-step"><span>⌁</span><div><b>What happens next?</b><p>After field verification, your application will be sent to the District Officer for approval.</p></div></div></div><div className="section-head fund-head"><div><span className="eyebrow">STAGED FUND RELEASE</span><h2>Grant disbursement plan</h2><p>Funds are released in stages as your application moves forward.</p></div><div className="amount-box"><small>TOTAL APPROVED BENEFIT</small><b>{scheme.amount}</b></div></div><div className="release-list">{stages.map((s, i) => <div className="release" key={s.name}><div className={`release-dot ${s.done ? 'released' : ''}`}>{s.done ? '✓' : i + 1}</div><div className="release-main"><span>{s.name}</span><b>{s.amount} <small>({[30,40,30][i]}%)</small></b></div><div className="release-date"><b>{s.date}</b><span className={s.done ? 'pill green-pill' : 'pill gray'}>{s.status}</span></div></div>)}</div></section> }

function CriteriaModal({ scheme, result, close, confirm }) { return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="criteria-modal"><button className="modal-close" onClick={close}>x</button><div className="criteria-title"><span className="scheme-icon">{scheme.icon}</span><div><span className="eyebrow">SCHEME CRITERIA CHECK</span><h2>{scheme.short}</h2></div></div><div className={result.eligible ? 'eligibility-result yes' : 'eligibility-result no'}><b>{result.eligible ? 'Eligible to apply' : 'Profile criteria not met'}</b><p>{result.message}</p></div><div className="criteria-check"><span>Annual family income</span><b>{result.incomeEligible ? 'Within limit' : 'Above limit'}</b><small>Maximum permitted: Rs. {Number(result.maxIncomeLimit).toLocaleString('en-IN')}</small></div><div className="criteria-check"><span>Social category</span><b>{result.categoryEligible ? 'Accepted' : 'Not accepted'}</b><small>Eligible categories: {result.allowedCategories.join(', ')}</small></div><div className="document-list"><span>REQUIRED DOCUMENT CHECKLIST</span>{result.requiredDocuments.map(doc => <label key={doc}><input type="checkbox" defaultChecked /> <b>{doc}</b><small>Ready for upload</small></label>)}</div>{result.eligible ? <button className="primary full" onClick={confirm}>Confirm and submit application <span>-&gt;</span></button> : <button className="outline full" onClick={close}>Review my profile</button>}</div></div> }

createRoot(document.getElementById('root')).render(<App />);
